update Bash configuration

diff --git a/.bashrc.d/rf b/.bashrc.d/rf
--- a/.bashrc.d/rf
+++ b/.bashrc.d/rf
@@ -1,3 +1,7 @@
 rf() {
-	rg --color='ansi' $@ | fzf --ansi --preview=''
+	if [ $# -lt 1 ]; then
+		printf 'rf: error: %s\n' 'expected at least one argument' 1>&2
+		return 2
+	fi
+	rg --color=ansi "$@" | fzf --ansi
 }
